-- MySQL Script generated by MySQL Workbench
-- sáb 05 fev 2022 20:00:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema imoveis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema imoveis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imoveis` DEFAULT CHARACTER SET utf8 ;
USE `imoveis` ;

-- -----------------------------------------------------
-- Table `imoveis`.`imoveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imoveis`.`imoveis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `link` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `link_UNIQUE` (`link` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imoveis`.`notificacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imoveis`.`notificacoes` (
  `link` VARCHAR(500) NOT NULL,
  `status` TINYINT NOT NULL,
  `imoveis_id` INT NOT NULL,
  PRIMARY KEY (`imoveis_id`),
  INDEX `fk_notificacoes_imoveis_idx` (`imoveis_id` ASC) VISIBLE,
  UNIQUE INDEX `link_UNIQUE` (`link` ASC) VISIBLE,
  CONSTRAINT `fk_notificacoes_imoveis`
    FOREIGN KEY (`imoveis_id`)
    REFERENCES `imoveis`.`imoveis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `imoveis`;

DELIMITER $$
USE `imoveis`$$
CREATE DEFINER = CURRENT_USER TRIGGER `imoveis`.`imoveis_AFTER_INSERT` AFTER INSERT ON `imoveis` FOR EACH ROW
BEGIN
	INSERT INTO `notificacoes`(`link`,`status`,`imoveis_id`)
    VALUES(new.link,0,new.id);
END$$

USE `imoveis`$$
CREATE DEFINER = CURRENT_USER TRIGGER `imoveis`.`imoveis_BEFORE_DELETE` BEFORE DELETE ON `imoveis` FOR EACH ROW
BEGIN
	DELETE FROM `notificacoes` WHERE `imoveis_id` = OLD.id;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
